const { Router } = require('express')
const crypto = require('crypto')
const { requireAuth } = require('../../core/auth')
const { requirePermission } = require('../../core/permissions')
const { readDb, writeDb, runMssqlScalar, DB_MODE, MSSQL_RELATIONAL_MODE } = require('../../core/db')
const { addAudit } = require('../../core/audit')
const { notifyUser } = require('../messaging/routes')
const { sendEmail } = require('../messaging/email')

const router = Router()
function isMssqlMode(){return MSSQL_RELATIONAL_MODE && (DB_MODE==='mssql'||DB_MODE==='sqlserver')}
function sendJson(res,status,data){res.status(status).json(data)}
function nowIso(){return new Date().toISOString()}
function nextId(items){return items.reduce((m,i)=>Math.max(m,Number(i.id||0)),0)+1}
function mssqlJson(sql,params={}){const r=runMssqlScalar(`DECLARE @p nvarchar(max) = @json;\n${sql}`,{jsonInput:JSON.stringify(params)});return String(r||'').trim()?JSON.parse(r):null}
function mssqlArray(sql,params={}){return mssqlJson(sql,params)||[]}
function mssqlObject(sql,params={}){return mssqlArray(sql,params)[0]||null}
function ensureDb(db){db.secretariat=db.secretariat||{}; for(const k of ['registry','correspondenceTracking','appointments']) db.secretariat[k]=Array.isArray(db.secretariat[k])?db.secretariat[k]:[]; return db.secretariat}
function deptName(db,id){return (db.departments||db.core?.departments||[]).find(d=>String(d.id)===String(id))?.denumire||''}
function userName(db,id){const u=(db.users||db.core?.users||[]).find(x=>String(x.id)===String(id)); return [u?.prenume,u?.nume].filter(Boolean).join(' ')||u?.name||''}
function findDepartmentId(db,value){const raw=String(value||'').trim(); if(!raw)return ''; const normalized=raw.toLowerCase(); const departments=db.departments||db.core?.departments||[]; const found=departments.find(d=>String(d.id)===raw)||departments.find(d=>String(d.cod||'').toLowerCase()===normalized)||departments.find(d=>String(d.denumire||d.name||'').toLowerCase()===normalized); return found?.id||raw}
function resolveRegistryAssignment(db,body){const deptId=findDepartmentId(db,body.dept_destinatar||body.departament||body.department||body.dept_id); const userId=body.user_responsabil||body.repartizat_catre||body.user_id||''; return {...body,dept_destinatar:deptId,user_responsabil:userId}}
function registryPrefix(tip){const raw=String(tip||'intrare_externa'); if(raw==='iesire_externa')return 'E'; if(raw==='intrare_interna'||raw==='iesire_interna')return 'INT'; return 'I'}
function nextRegistryNumber(items,tip){const year=new Date().getFullYear(); const prefix=registryPrefix(tip); const n=items.filter(x=>Number(x.an)===year&&registryPrefix(x.tip)===prefix).reduce((m,x)=>Math.max(m,Number(x.nr_curent||0)),0)+1; return {nr_curent:n,format:`${prefix}-${String(n).padStart(3,'0')}/${year}`,an:year,prefix}}
function notifyAssignment(db, deptId, userId, payload){ if(userId) notifyUser(userId,'secretariat_assigned',payload); (db.users||[]).filter(u=>String(u.departmentId||u.department_id)===String(deptId)).forEach(u=>notifyUser(u.id,'secretariat_assigned',payload)) }
async function maybeEmailRegistry(db, body, item){ if(!body.trimite_email)return; const targets=(db.users||[]).filter(u=>String(u.id)===String(body.user_responsabil)||String(u.departmentId||u.department_id)===String(body.dept_destinatar)).map(u=>u.email).filter(Boolean); for(const to of targets) await sendEmail({to,subject:`Registratură ${item.nr_inregistrare}`,body:`<p>${item.subiect||'Document nou repartizat'}</p>`},db).catch(()=>{}) }

router.get('/secretariat/registry',(req,res,next)=>{try{
  const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:view'))return
  if(isMssqlMode())return sendJson(res,200,mssqlArray(`SELECT r.*, d.denumire AS dept_destinatar_name, u.nume AS user_responsabil_name FROM secretariat.registry r LEFT JOIN core.departments d ON d.id=r.dept_destinatar LEFT JOIN core.users u ON u.id=r.user_responsabil WHERE (NULLIF(JSON_VALUE(@p,'$.tip'),'') IS NULL OR r.tip=JSON_VALUE(@p,'$.tip')) AND (NULLIF(JSON_VALUE(@p,'$.status'),'') IS NULL OR r.status=JSON_VALUE(@p,'$.status')) AND (NULLIF(JSON_VALUE(@p,'$.de_la'),'') IS NULL OR r.data_inregistrare>=TRY_CONVERT(datetime2,JSON_VALUE(@p,'$.de_la'))) AND (NULLIF(JSON_VALUE(@p,'$.pana_la'),'') IS NULL OR r.data_inregistrare<DATEADD(day,1,TRY_CONVERT(datetime2,JSON_VALUE(@p,'$.pana_la')))) AND (NULLIF(JSON_VALUE(@p,'$.q'),'') IS NULL OR r.subiect LIKE N'%'+JSON_VALUE(@p,'$.q')+N'%' OR r.nr_inregistrare LIKE N'%'+JSON_VALUE(@p,'$.q')+N'%') ORDER BY r.data_inregistrare DESC FOR JSON PATH;`,req.query))
  const db=readDb(); let rows=ensureDb(db).registry
  if(req.query.tip)rows=rows.filter(x=>x.tip===req.query.tip); if(req.query.status)rows=rows.filter(x=>x.status===req.query.status); if(req.query.de_la)rows=rows.filter(x=>x.data_inregistrare>=req.query.de_la); if(req.query.pana_la)rows=rows.filter(x=>x.data_inregistrare<=req.query.pana_la); if(req.query.q)rows=rows.filter(x=>String(x.subiect||x.nr_inregistrare||'').toLowerCase().includes(String(req.query.q).toLowerCase()))
  sendJson(res,200,rows.map(x=>({...x,dept_destinatar_name:deptName(db,x.dept_destinatar),user_responsabil_name:userName(db,x.user_responsabil)})))
}catch(e){next(e)}})

router.post('/secretariat/registry/next-number',(req,res,next)=>{try{
  const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:view'))return
  if(isMssqlMode())return sendJson(res,200,mssqlObject(`DECLARE @year int=YEAR(GETDATE()); DECLARE @tip nvarchar(40)=COALESCE(NULLIF(JSON_VALUE(@p,'$.tip'),''),N'intrare_externa'); DECLARE @prefix nvarchar(5)=CASE WHEN @tip=N'iesire_externa' THEN N'E' WHEN @tip IN (N'intrare_interna',N'iesire_interna') THEN N'INT' ELSE N'I' END; DECLARE @nr int=COALESCE((SELECT MAX(nr_curent)+1 FROM secretariat.registry WHERE an=@year AND nr_inregistrare LIKE @prefix+N'-%'),1); SELECT @nr AS nr_curent, CONCAT(@prefix,N'-',RIGHT(CONCAT(N'000',@nr),3),N'/',@year) AS format, @prefix AS prefix FOR JSON PATH;`,req.body||{}))
  sendJson(res,200,nextRegistryNumber(ensureDb(readDb()).registry,req.body?.tip||req.query?.tip))
}catch(e){next(e)}})

router.post('/secretariat/registry',(req,res,next)=>{try{
  const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:registry'))return
  const db=readDb()
  const body=resolveRegistryAssignment(db,req.body||{})
  if(isMssqlMode()){
    const item=mssqlObject(`DECLARE @year int=YEAR(GETDATE()); DECLARE @tip nvarchar(40)=COALESCE(NULLIF(JSON_VALUE(@p,'$.tip'),''),N'intrare_externa'); DECLARE @prefix nvarchar(5)=CASE WHEN @tip=N'iesire_externa' THEN N'E' WHEN @tip IN (N'intrare_interna',N'iesire_interna') THEN N'INT' ELSE N'I' END; DECLARE @nr int=COALESCE((SELECT MAX(nr_curent)+1 FROM secretariat.registry WHERE an=@year AND nr_inregistrare LIKE @prefix+N'-%'),1); INSERT INTO secretariat.registry (uuid,tip,an,nr_curent,nr_inregistrare,expeditor,destinatar,subiect,dept_destinatar,user_responsabil,status,fisier_path) VALUES (JSON_VALUE(@p,'$.uuid'),@tip,@year,@nr,CONCAT(@prefix,N'-',RIGHT(CONCAT(N'000',@nr),3),N'/',@year),NULLIF(JSON_VALUE(@p,'$.expeditor'),''),NULLIF(JSON_VALUE(@p,'$.destinatar'),''),JSON_VALUE(@p,'$.subiect'),NULLIF(JSON_VALUE(@p,'$.dept_destinatar'),''),NULLIF(JSON_VALUE(@p,'$.user_responsabil'),''),CASE WHEN NULLIF(JSON_VALUE(@p,'$.dept_destinatar'),'') IS NULL THEN N'inregistrat' ELSE N'repartizat' END,NULLIF(JSON_VALUE(@p,'$.fisier_path'),'')); DECLARE @id int=SCOPE_IDENTITY(); IF NULLIF(JSON_VALUE(@p,'$.dept_destinatar'),'') IS NOT NULL INSERT INTO secretariat.correspondence_tracking (registry_id,dept_id,user_id,termen_raspuns,status) VALUES (@id,JSON_VALUE(@p,'$.dept_destinatar'),NULLIF(JSON_VALUE(@p,'$.user_responsabil'),''),TRY_CONVERT(date,NULLIF(JSON_VALUE(@p,'$.termen_raspuns'),'')),N'repartizat'); SELECT TOP 1 * FROM secretariat.registry WHERE id=@id FOR JSON PATH;`,{...body,uuid:crypto.randomUUID()})
    maybeEmailRegistry(db,body,item).finally(()=>{}); addAudit(db,auth.user,'secretariat_registry_created',item?.nr_inregistrare); writeDb(db); return sendJson(res,201,item)
  }
  const sec=ensureDb(db); const nr=nextRegistryNumber(sec.registry,body.tip); const item={id:nextId(sec.registry),uuid:crypto.randomUUID(),tip:body.tip||'intrare_externa',an:nr.an,nr_curent:nr.nr_curent,nr_inregistrare:nr.format,...body,status:body.dept_destinatar?'repartizat':'inregistrat',created_at:nowIso(),updated_at:null}; sec.registry.push(item)
  if(body.dept_destinatar)sec.correspondenceTracking.push({id:nextId(sec.correspondenceTracking),registry_id:item.id,dept_id:body.dept_destinatar,user_id:body.user_responsabil||null,termen_raspuns:body.termen_raspuns||null,status:'repartizat',created_at:nowIso()})
  maybeEmailRegistry(db,body,item).finally(()=>{}); addAudit(db,auth.user,'secretariat_registry_created',item.nr_inregistrare); writeDb(db); sendJson(res,201,item)
}catch(e){next(e)}})

router.post('/secretariat/registry/:id/assign',(req,res,next)=>{try{
  const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:assign'))return
  const db=readDb()
  if(isMssqlMode()){
    const item=mssqlObject(`UPDATE secretariat.registry SET status=N'repartizat', dept_destinatar=JSON_VALUE(@p,'$.dept_id'), user_responsabil=NULLIF(JSON_VALUE(@p,'$.user_id'),''), updated_at=sysdatetime() WHERE id=TRY_CONVERT(int,JSON_VALUE(@p,'$.id')); INSERT INTO secretariat.correspondence_tracking (registry_id,dept_id,user_id,termen_raspuns,status) VALUES (TRY_CONVERT(int,JSON_VALUE(@p,'$.id')),JSON_VALUE(@p,'$.dept_id'),NULLIF(JSON_VALUE(@p,'$.user_id'),''),TRY_CONVERT(date,NULLIF(JSON_VALUE(@p,'$.termen_raspuns'),'')),N'repartizat'); SELECT TOP 1 * FROM secretariat.registry WHERE id=TRY_CONVERT(int,JSON_VALUE(@p,'$.id')) FOR JSON PATH;`,{...req.body,id:req.params.id})
    notifyAssignment(db,req.body.dept_id,req.body.user_id,item); addAudit(db,auth.user,'secretariat_registry_assigned',req.params.id); writeDb(db); return sendJson(res,200,item)
  }
  const sec=ensureDb(db); const item=sec.registry.find(x=>String(x.id)===String(req.params.id)); if(!item)return sendJson(res,404,{error:'Documentul nu a fost găsit.'}); Object.assign(item,{status:'repartizat',dept_destinatar:req.body.dept_id,user_responsabil:req.body.user_id||null,updated_at:nowIso()}); sec.correspondenceTracking.push({id:nextId(sec.correspondenceTracking),registry_id:item.id,dept_id:req.body.dept_id,user_id:req.body.user_id||null,termen_raspuns:req.body.termen_raspuns||null,status:'repartizat',created_at:nowIso()}); notifyAssignment(db,req.body.dept_id,req.body.user_id,item); addAudit(db,auth.user,'secretariat_registry_assigned',item.nr_inregistrare); writeDb(db); sendJson(res,200,item)
}catch(e){next(e)}})

router.get('/secretariat/registry/:id/tracking',(req,res,next)=>{try{const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:view'))return; if(isMssqlMode())return sendJson(res,200,mssqlArray(`SELECT * FROM secretariat.correspondence_tracking WHERE registry_id=TRY_CONVERT(int,JSON_VALUE(@p,'$.id')) ORDER BY created_at DESC FOR JSON PATH;`,req.params)); sendJson(res,200,ensureDb(readDb()).correspondenceTracking.filter(x=>String(x.registry_id)===String(req.params.id)))}catch(e){next(e)}})

router.get('/secretariat/appointments',(req,res,next)=>{try{const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:view'))return; if(isMssqlMode())return sendJson(res,200,mssqlArray(`SELECT * FROM secretariat.appointments WHERE (NULLIF(JSON_VALUE(@p,'$.tip'),'') IS NULL OR tip=JSON_VALUE(@p,'$.tip')) AND (NULLIF(JSON_VALUE(@p,'$.de_la'),'') IS NULL OR data_start>=TRY_CONVERT(datetime2,JSON_VALUE(@p,'$.de_la'))) AND (NULLIF(JSON_VALUE(@p,'$.pana_la'),'') IS NULL OR data_start<DATEADD(day,1,TRY_CONVERT(datetime2,JSON_VALUE(@p,'$.pana_la')))) ORDER BY data_start ASC FOR JSON PATH;`,req.query)); let rows=ensureDb(readDb()).appointments; if(req.query.tip)rows=rows.filter(x=>x.tip===req.query.tip); if(req.query.de_la)rows=rows.filter(x=>x.data_start>=req.query.de_la); if(req.query.pana_la)rows=rows.filter(x=>x.data_start<=req.query.pana_la); sendJson(res,200,rows)}catch(e){next(e)}})
router.post('/secretariat/appointments',(req,res,next)=>{try{const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:appointments'))return; const db=readDb(); const body={...req.body,uuid:crypto.randomUUID(),participanti_json:JSON.stringify(req.body.participanti||[])}; if(isMssqlMode()){const item=mssqlObject(`INSERT INTO secretariat.appointments (uuid,tip,titlu,data_start,data_sfarsit,participanti_json,status) VALUES (JSON_VALUE(@p,'$.uuid'),NULLIF(JSON_VALUE(@p,'$.tip'),''),JSON_VALUE(@p,'$.titlu'),TRY_CONVERT(datetime2,JSON_VALUE(@p,'$.data_start')),TRY_CONVERT(datetime2,NULLIF(JSON_VALUE(@p,'$.data_sfarsit'),'')),JSON_VALUE(@p,'$.participanti_json'),COALESCE(NULLIF(JSON_VALUE(@p,'$.status'),''),N'programat')); SELECT TOP 1 * FROM secretariat.appointments WHERE id=SCOPE_IDENTITY() FOR JSON PATH;`,body); addAudit(db,auth.user,'secretariat_appointment_created',item?.uuid); writeDb(db); return sendJson(res,201,item)} const sec=ensureDb(db); const item={id:nextId(sec.appointments),...body,status:body.status||'programat',created_at:nowIso(),updated_at:null}; sec.appointments.push(item); addAudit(db,auth.user,'secretariat_appointment_created',item.uuid); writeDb(db); sendJson(res,201,item)}catch(e){next(e)}})
router.patch('/secretariat/appointments/:uuid/minuta',(req,res,next)=>{try{const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:appointments'))return; const db=readDb(); if(isMssqlMode()){const item=mssqlObject(`UPDATE secretariat.appointments SET minuta=JSON_VALUE(@p,'$.minuta'), status=N'finalizat', updated_at=sysdatetime() WHERE uuid=JSON_VALUE(@p,'$.uuid'); SELECT TOP 1 * FROM secretariat.appointments WHERE uuid=JSON_VALUE(@p,'$.uuid') FOR JSON PATH;`,{...req.body,uuid:req.params.uuid}); addAudit(db,auth.user,'secretariat_appointment_minutes',req.params.uuid); writeDb(db); return sendJson(res,200,item)} const sec=ensureDb(db); const item=sec.appointments.find(x=>x.uuid===req.params.uuid); if(!item)return sendJson(res,404,{error:'Programarea nu a fost găsită.'}); item.minuta=req.body.minuta; item.status='finalizat'; item.updated_at=nowIso(); addAudit(db,auth.user,'secretariat_appointment_minutes',item.uuid); writeDb(db); sendJson(res,200,item)}catch(e){next(e)}})
router.get('/secretariat/overdue',(req,res,next)=>{try{const auth=requireAuth(req,res); if(!auth)return; if(!requirePermission(auth,res,'secretariat:view'))return; if(isMssqlMode())return sendJson(res,200,mssqlArray(`SELECT cr.*, r.nr_inregistrare, r.subiect, d.denumire as dept_nume FROM secretariat.correspondence_tracking cr JOIN secretariat.registry r ON r.id=cr.registry_id JOIN core.departments d ON d.id=cr.dept_id WHERE cr.termen_raspuns < GETDATE() AND cr.status NOT IN (N'raspuns_dat') ORDER BY cr.termen_raspuns ASC FOR JSON PATH;`)); const db=readDb(); const today=new Date().toISOString().slice(0,10); sendJson(res,200,ensureDb(db).correspondenceTracking.filter(x=>x.termen_raspuns<today&&x.status!=='raspuns_dat').map(x=>({...x,dept_nume:deptName(db,x.dept_id)})))}catch(e){next(e)}})

module.exports = router
