const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')
const { createPublicToken, tokenHash, safeTokenMatch, normalizePublicDecision, publicQuoteView, createRateLimiter } = require('../modules/crm/public-service')
const root = path.resolve(__dirname, '../..')
const repository = fs.readFileSync(path.join(root, 'server/modules/crm/quote-repository.js'), 'utf8')
const publicRoutes = fs.readFileSync(path.join(root, 'server/modules/crm/public-routes.js'), 'utf8')
const app = fs.readFileSync(path.join(root, 'server/app.js'), 'utf8')
const migration = fs.readFileSync(path.join(root, 'db/migrations/073_crm_quote_public_links_sprint_4.sql'), 'utf8')
const publicPage = fs.readFileSync(path.join(root, 'client/src/pages/PublicQuotePage.jsx'), 'utf8')

test('tokenul public este aleator, se verifică doar prin hash și nu se confundă cu alt token', () => {
  const token = createPublicToken()
  assert.match(token, /^[A-Za-z0-9_-]{40,}$/)
  assert.equal(tokenHash(token).length, 64)
  assert.equal(safeTokenMatch(token, tokenHash(token)), true)
  assert.equal(safeTokenMatch(`${token}x`, tokenHash(token)), false)
})
test('decizia publică acceptă strict acceptare/refuz și date de contact sigure', () => {
  assert.equal(normalizePublicDecision({ decision: 'accepted', decided_by_name: ' Client ' }).decision, 'accepted')
  assert.throws(() => normalizePublicDecision({ decision: 'order' }), /Decizia nu este validă/)
  assert.throws(() => normalizePublicDecision({ decision: 'declined', decided_by_email: 'invalid' }), /Emailul nu este valid/)
})
test('proiecția publică exclude note interne, identificatori și audit', () => {
  const view = publicQuoteView({ id: 7, notes_internal: 'secret', responsible_user_id: 'admin', quote_number: 'OF-1', revision_number: 2, title: 'Oferta', account_name: 'Client', currency: 'RON', total: 100, lines: [{ id: 8, position: 1, description: 'Serviciu', line_total: 100 }] })
  assert.equal(view.notes_internal, undefined)
  assert.equal(view.id, undefined)
  assert.equal(view.lines[0].id, undefined)
  assert.equal(view.quote_number, 'OF-1')
})
test('rate limiterul limitează independent cererile repetate', () => {
  const limited = createRateLimiter({ limit: 2, windowMs: 10000 })
  assert.equal(limited('client-a'), false)
  assert.equal(limited('client-a'), false)
  assert.equal(limited('client-a'), true)
  assert.equal(limited('client-b'), false)
})
test('repository-ul fixează linkul pe revizie, permite revocare și decizie idempotentă', () => {
  ;['quote_revision','status=N\'active\'','status=N\'revoked\'','recordPublicDecision','token_hash'].forEach(fragment => assert.match(repository, new RegExp(fragment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))))
  assert.match(migration, /UX_crm_quote_decisions_revision/)
  assert.match(repository, /status IN\(N'approved',N'sent'\)/)
})
test('rutele publice sunt neautentificate, no-store și nu expun tokenul în loguri', () => {
  assert.match(publicRoutes, /router\.get\('\/quote\/:token'/)
  assert.match(publicRoutes, /router\.post\('\/quote\/:token\/decision'/)
  assert.match(publicRoutes, /Cache-Control/)
  assert.match(publicRoutes, /Referrer-Policy/)
  assert.match(publicRoutes, /X-Robots-Tag/)
  assert.match(app, /\[redacted\]/)
})
test('pagina publică cere o confirmare explicită atât pentru acceptare, cât și pentru refuz', () => {
  assert.match(publicPage, /setDecision\('accepted'\)/)
  assert.match(publicPage, /Confirmă acceptarea/)
  assert.match(publicPage, /Confirmă refuzul/)
})
